#!/usr/bin/env node

'use strict';

var env = process.env
  , url = require('url')
  , async = require('async')
  , kuler = require('kuler')
  , prompt = require('prompt')
  , argv = require('argh').argv 
  , GitHulk = require('githulk')
  , Registry = require('npm-registry')
  , who = require('shelljs').exec('npm whoami', { silent: true }).output.trim();

//
// Handle a --help flag
//
if (argv.help) {
  return require('fs').readFileSync(__dirname +'/usage', 'utf-8')
  .split('\n')
  .forEach(function output(line) {
    console.log(kuler('help:', 'hotpink'), line);
  });
}

//
// Prompt for the information that was not supplied using cli flags, this is
// required information and needed to continue with the spidering of data.
//
prompt.override = argv;
prompt.start();

//
// Get some sane defaults that we can spider from the user's system
//
prompt.get([
  { name: 'npm', default: who },
  { name: 'github', default: who },
  { name: 'token', default: env.GITHULK_TOKEN || env.GITHULK || env.GITHUB_TOKEN  },
  { name: 'registry', default: Registry.mirrors.nodejitsu }
], function received(err, details) {
  if (err) throw err;
  
  var npm = new Registry({ registry: details.registry })
    , github = new GitHulk({ token: details.token });

  async.parallel({
    npm: function download(next) {
      npm.users.list(details.npm, function list(err, packages) {
        if (err) return next(err);

        async.map(packages, function map(data, next) {
          npm.packages.get(data.name, function (err, data) {
            if (err) return next(err);

            //
            // The npm module returns arrays by default, we just want only item.
            //
            next(err, data[0]);
          });
        }, next);
      });
    },

    github: function download(next) {
      github.organizations.list(function err(err, orgs) {
        if (err) return next(err);

        //
        // Mark as organization so we can add it repo's that we need to check.
        //
        orgs = orgs.map(function map(org) {
          org.organization = true;
          return org;
        });

        //
        // Add our username in to the list of organizations that we need to
        // spider.
        //
        orgs.push({ login: details.github });

        async.map(orgs, function map(data, next) {
          github.repository.list(data.login, { 
            organization: data.organization 
          }, next);
        }, function failed(err, listoflists) {
          if (err) return next(err);

          var list = [];

          listoflists.forEach(function each(repos) {
            Array.prototype.push.apply(list, repos);
          });
          
          async.map(list, function map(repo, next) {
            repo.npm = {};

            github.repository.contents(repo.full_name, { 
              path: 'package.json'
            }, function (err, data) {
              if (err || !data || !data.length) return next(undefined, repo);

              //
              // Parse the contents of repository to see if we can find
              // a package.json so we will have something easier to match
              // against.
              //
              try { 
                data = JSON.parse((new Buffer(data[0].contents, data[0].encoding)).toString('utf-8')); 
              } catch (e) { return next(undefined, repo); }

              repo.json = data;
              next(undefined, repo);
            });
          }, next);
        });
      });
    }
  }, function downloaded(err, data) {
    if (err) throw err;

    //
    // Reduce the amount of data that we received from GitHub so we only got the
    // bare minimum of information that we need.
    //
    data.github = data.github.map(function map(repo) {
      return {
        description: repo.description,      // Fallback for npm description.
        url: repo.html_url,                 // For matching with npm modules.
        fork: repo.fork,                    // Might want to exclude forks, not OC.
        name: repo.name,                    // Name of module
        created: new Date(repo.created_at), // Created at.
        json: repo.npm                      // Reference to package.json in repo.
      };
    });

    //
    // Reduce the amount of data from npm to only contain the useful
    // information, this should somewhat mirror the data available from git for
    // matching.
    //
    data.npm = data.npm.map(function map(pkg) {
      return {
        description: pkg.description,     // Description of the module
        url: (pkg.repository || {}).url,  // Possible repository URL.
        fork: false,                      // Sorry, we don't understand forks.
        name: pkg.name,                   // Name of the module.
        created: new Date(pkg.created),   // Creation date.
        author: (pkg.author || {}).name   // Name of the author.
      };
    });

    var duplicate = []
      , unique = [];

    async.eachSeries(data.npm, function find(pkg, next) {
      /**
       * Simple helper method for adding a selected package to the unique array.
       * 
       * @param {Object} pkg npm package contents.
       * @param {Object} match github contents.
       * @api private
       */
      function add(pkg, match) {
        duplicate.push(match);
        unique.push({
          name: pkg.name || match.name,
          description: match.description.length > pkg.description.length
          ? match.description
          : pkg.description,
          fork: match.fork,
          created: +pkg.created > +match.created
          ? match.created
          : pkg.created,
          author: pkg.author
        });

        next();
      }

      //
      // Attempt to match the npm data with github repositories.
      //
      var match = data.github.filter(function filter(repo) {
        return repo.name === pkg.name
        || url.parse(repo.url || '').pathname === url.parse(pkg.url || '').pathname
        || repo.json.name === pkg.name
        || repo.json.description === pkg.description
        ;
      });

      if (!match.length) {
        unique.push(pkg);
        return next();
      }

      //
      // Possible problem situation here, we've found multiple matches for
      // a single package so we have to prompt the user in to selecting or
      // declining the matching repository.
      //
      if (match.length > 1) {
        console.log('');
        console.log('Conflict found, can\'t find an unique GitHub repository for the following module:');
        console.log('  name: '+ kuler(pkg.name, 'green'));
        console.log('  desc: '+ pkg.description);
        console.log('To resolve this conflict please supply one of the following options:');
        console.log('');

        match.forEach(function each(repo, index) {
          console.log(kuler(index, 'green') +':');
          console.log('  name: '+ repo.name);
          console.log('  desc: '+ repo.description);
          console.log('  fork: '+ repo.fork);
          console.log('  url: '+ repo.url);
        });

        console.log('');
        console.log('To decline all options supply: '+ kuler('x', 'red'));
        console.log('');
        return prompt.get('choice', function prompted(err, selected) {
          if (err) throw err;

          if (selected.choice === 'x') {
            unique.push(pkg);
            return next();
          }

          add(pkg, match[+selected.choice]);
        });
      }

      add(pkg, match.pop());
    }, function () {
      Array.prototype.push.apply(unique, data.github.filter(function filter(repo) {
        return !~duplicate.indexOf(repo);
      }));

      //
      // @TODO run through formatters;
      //
      require('./formatters/'+ (argv.format || 'markdown'))(unique.sort(function (a, b) {
        return a.created > b.created;
      }));
    });
  });
});
